- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Install PHP and PHP-FPM
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php8.1-fpm

- name: Configure Nginx
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload Nginx

- name: Start and enable Nginx service
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started

- name: Start and enable PHP-FPM service
  ansible.builtin.systemd:
    name: php8.1-fpm
    enabled: true
    state: started

- name: Create DocumentRoot directory
  ansible.builtin.file:
    path: /opt/nginx/ansible
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Deploy index.php
  ansible.builtin.copy:
    content: "<?php phpinfo(); ?>"
    dest: /opt/nginx/ansible/index.php
    owner: www-data
    group: www-data 
    mode: '0644'
    