---
# defaults file for vsftpd_role
vsftpd_role_anonymous_enable: false
vsftpd_role_local_enable: true
vsftpd_role_write_enable: true
vsftpd_role_local_umask: "022"
vsftpd_role_dirmessage_enable: true
vsftpd_role_use_localtime: true
vsftpd_role_xferlog_enable: true
vsftpd_role_connect_from_port_20: true
vsftpd_role_chroot_local_user: true
vsftpd_role_listen: true
vsftpd_role_secure_chroot_dir: "/var/run/vsftpd/empty"
vsftpd_role_pasv_enable: true
vsftpd_role_pasv_min_port: 10000
vsftpd_role_pasv_max_port: 10100
vsftpd_role_user_sub_token: "$USER"
vsftpd_role_local_root: "/home/$USER/ftp"
