---
# tasks file for vsftpd_role

- name: Install vsftpd
  ansible.builtin.apt:
    name: vsftpd
    state: present

- name: Ensure vsftpd is configured
  ansible.builtin.template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart vsftpd

- name: Ensure vsftpd service is enabled and started
  ansible.builtin.systemd:
    name: vsftpd
    state: started
    enabled: true
