---
- name: Install and configure nginx  # Имя плейбука - Устанавливает и настраивает nginx
  hosts: localhost  # Указываем, что плейбук будет выполняться на локальной машине
  become: true  # Включаем повышение привилегий (sudo)
  become_method: ansible.builtin.sudo  # Указываем, что для повышения привилегий будет использоваться sudo

  tasks:  # Секция задач, которые будут выполняться
    - name: Update apt package index  # Имя задачи - Обновление индекса пакетов apt
      ansible.builtin.apt:  # Используем модуль apt для управления пакетами на Debian-based системах
        update_cache: true  # Указываем, что нужно обновить кэш пакетов

    - name: Install nginx  # Имя задачи - Установка nginx
      ansible.builtin.apt:  # Используем модуль apt для установки пакета
        name: nginx  # Имя пакета для установки
        state: present  # Указываем, что пакет должен быть установлен

    - name: Ensure nginx is started and enabled  # Имя задачи - Запуск и включение nginx
      ansible.builtin.systemd:  # Используем модуль systemd для управления сервисами
        name: nginx  # Имя сервиса
        state: started  # Указываем, что сервис должен быть запущен
        enabled: true  # Указываем, что сервис должен быть включен при загрузке системы

    - name: Get hostname  # Имя задачи - Получение имени хоста
      ansible.builtin.command:  # Используем модуль command для выполнения команды hostname
        cmd: hostname  # Команда для выполнения
      register: hostname  # Сохраняем результат выполнения команды в переменную hostname
      changed_when: false  # Указываем, что команда не изменяет состояние системы

    - name: Get total memory  # Имя задачи - Получение общей памяти
      ansible.builtin.command:  # Используем модуль command для выполнения команды
        cmd: grep MemTotal /proc/meminfo  # Команда для получения информации о памяти
      register: meminfo  # Сохраняем результат выполнения команды в переменную meminfo
      changed_when: false  # Указываем, что команда не изменяет состояние системы

    - name: Create custom index.html  # Имя задачи - Создание кастомного index.html
      ansible.builtin.copy:  # Используем модуль copy для создания файла
        content: |  # Указываем содержимое файла
          <html>
          <head><title>Machine Info</title></head>
          <body>
          <h1>Machine Information</h1>
          <p>Hostname: {{ hostname.stdout }}</p>
          <p>Total Memory: {{ meminfo.stdout }}</p>
          </body>
          </html>
        dest: /usr/share/nginx/html/index.html  # Указываем путь, куда будет скопирован файл
        mode: '0644'  # Устанавливаем права доступа к файлу
