---
- name: Install or remove Postfix based on tags
  hosts: all
  become: true
  tasks:
    - name: Install Postfix
      ansible.builtin.package:
        name: postfix
        state: present
      tags: init

    - name: Ensure Postfix is running and enabled
      ansible.builtin.service:
        name: postfix
        state: started
        enabled: true
      tags: init

    - name: Remove Postfix
      ansible.builtin.package:
        name: postfix
        state: absent
      tags: drop
