---
- name: Remove superusers group and users
  hosts: all
  become: true
  tasks:
    - name: Remove 'user2' from the system
      ansible.builtin.user:
        name: user2
        state: absent
        remove: true  # This will also remove the user's home directory and mail spool

    - name: Remove 'user3' from the system
      ansible.builtin.user:
        name: user3
        state: absent
        remove: true  # This will also remove the user's home directory and mail spool

    - name: Remove 'superusers' group from the system
      ansible.builtin.group:
        name: superusers
        state: absent

    - name: Remove 'superusers' entry from sudoers file
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: '^%superusers ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
